services:
  edge_server:
    image: harbor.containerleaks.com/acporj2/edge_server@sha256:01de2ab0f58f250232173e39604732b9c3a4a676edf18e7b034efbe98990efe4
    restart: always
    ports: 
      - "8000:80"
    